# Parameters used to generate this project with aem-project-archetype

groupId=com.hdfc
artifactId=hdfcforms
version=1.0.0-SNAPSHOT
package=com.hdfc
appId=hdfcforms
appTitle=HDFC Forms
aemVersion=6.5.20
sdkVersion=latest
languageCountry=${languageCountry}
includeExamples=n
includeErrorHandler=n
frontendModule=general
singleCountry=y
includeDispatcherConfig=n
includeCif=n
includeForms=n
includeFormsenrollment=y
includeFormscommunications=y
sdkFormsVersion=latest
commerceEndpoint=https://hostname.com/graphql
datalayer=y
amp=n
enableDynamicMedia=n
enableSSR=n
precompiledScripts=n
includeFormsheadless=n
